In [2]:
import numpy as np

In [3]:
Key = np.array([[0,12,-12, 12, 6],
                [-3, -9, 9, 9, -6],
                [0, 0, 2, 4, -2],
                [-3, -17, 13, 3, -8],
                [0, 0, 4, -8, 0]])

In [4]:
Key.shape[0] == Key.shape[1]

True

In [5]:
np.linalg.det(Key) != 0

True

In [6]:
 n = 'PILLA'

In [7]:
import string


In [8]:
def preprocessing(n):
    n = n.replace(" ","").replace(",","").replace(".","").replace("'","").replace(":","").replace(";","")
    n  = n.lower()
    return n

def letters_plain(n):
    letters = []
    
    for i in range(0, len(n)):
        letters.append(n[i])
    return letters

def letter_number(letter):
    return string.ascii_lowercase.index(letter)

def number_letter(letter):
    return chr(int(number) +97)

def module(letter_index):
    
    while(letter_index <0):
        letter_index +=26
        
    while(letter_index >25):
        letter_index -=26
        
    return letter_index

In [9]:
preprocessing(n)

'pilla'

In [10]:
plain_text = letters_plain(n)

In [11]:
plain_text


['P', 'I', 'L', 'L', 'A']

In [12]:
plain_idx = []
for value in plain_text:
    plain_idx.append(ord(value))

In [13]:
plain_idx

[80, 73, 76, 76, 65]

In [14]:
plaintext_matrix = np.array(plain_idx)

In [15]:
plaintext_matrix

array([80, 73, 76, 76, 65])

In [16]:
plaintext_matrix.resize(5,5,refcheck=False)
plaintext_matrix

array([[80, 73, 76, 76, 65],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

## encryption

In [38]:
encryption =np.matmul(plaintext_matrix, Key)%29

In [39]:
encryption

array([[17, 26, 24,  5,  7],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]], dtype=int32)

In [40]:
encryption.resize(3,5, refcheck=False)
encryption

array([[17, 26, 24,  5,  7],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]], dtype=int32)

In [41]:
ciphertext = []
for i in encryption.tolist()[0]:
    ciphertext.append(chr(int(i) + 97))
    

In [42]:
encryption.tolist()[0]

[17, 26, 24, 5, 7]

In [43]:
ciphertext

['r', '{', 'y', 'f', 'h']

In [44]:
plain_text


['P', 'I', 'L', 'L', 'A']

## decryption

In [24]:
from sympy import Matrix

In [25]:
inv_key = Matrix(Key).inv_mod(29)

In [26]:
inv_key

Matrix([
[18, 17, 24,  2, 19],
[ 7, 15,  7, 14, 18],
[20, 28,  1,  1,  8],
[10, 14, 15, 15, 22],
[11, 27, 16,  2, 23]])

In [27]:
inv_key = np.array(inv_key)
inv_key

array([[18, 17, 24, 2, 19],
       [7, 15, 7, 14, 18],
       [20, 28, 1, 1, 8],
       [10, 14, 15, 15, 22],
       [11, 27, 16, 2, 23]], dtype=object)

In [28]:
inv_key = inv_key.astype(float)

In [29]:
np.matmul(Key, inv_key)%29


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
encryption.resize(5,3, refcheck= False)

In [30]:
decryption = np.matmul(encryption, inv_key) %29

In [31]:
decryption

array([[ 5., 17., 26.,  5., 14.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [32]:
decryption.resize(1,5, refcheck=False)

In [33]:
restored_text = [] 
for i in decryption.tolist()[0]:
    restored_text.append(chr(int(i) +97))

In [34]:
restored_text 

['f', 'r', '{', 'f', 'o']

In [35]:
decryption.tolist()[0]

[5.0, 17.0, 26.0, 5.0, 14.0]

## bruteforce

In [49]:
message = 'PILLA'
alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [50]:

for key in range(len(alphabet)):
    translated_message = ''
    for symbol in message:
        if symbol in alphabet:
            index = alphabet.find(symbol)
            index = index - key
            if index < 0:
                index = index + len(alphabet)
            translated_message = translated_message + alphabet[index]
        else:
            translated_message = translated_message + symbol
    print('Hacking key #%s: %s' % (key, translated_message))

Hacking key #0: PILLA
Hacking key #1: OHKKZ
Hacking key #2: NGJJY
Hacking key #3: MFIIX
Hacking key #4: LEHHW
Hacking key #5: KDGGV
Hacking key #6: JCFFU
Hacking key #7: IBEET
Hacking key #8: HADDS
Hacking key #9: GZCCR
Hacking key #10: FYBBQ
Hacking key #11: EXAAP
Hacking key #12: DWZZO
Hacking key #13: CVYYN
Hacking key #14: BUXXM
Hacking key #15: ATWWL
Hacking key #16: ZSVVK
Hacking key #17: YRUUJ
Hacking key #18: XQTTI
Hacking key #19: WPSSH
Hacking key #20: VORRG
Hacking key #21: UNQQF
Hacking key #22: TMPPE
Hacking key #23: SLOOD
Hacking key #24: RKNNC
Hacking key #25: QJMMB
